apiVersion: v2
name: demo-app
description: Minimal REST service returning a static message and current timestamp
keywords:
  - demo
  - fastapi
  - rest
  - timestamp
maintainers:
  - name: Norman Blakely
    email: nblakely@localnorm.com
version: 0.1.0
appVersion: "0.1.0"
type: application