# -- Image settings
image:
  repository: ghcr.io/your-org/demo-app
  tag: "0.1.0"
  pullPolicy: IfNotPresent

# -- App configuration
app:
  message: "Automate all the things!"

# -- Pod settings
replicaCount: 2
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

service:
  type: ClusterIP
  port: 80

# -- HTTP container port
containerPort: 8080

# -- Probes
livenessProbe:
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  path: /healthz
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
  successThreshold: 1

# -- Ingress (optional)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: demo.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: demo-tls
  #    hosts:
  #      - demo.example.com

# -- Horizontal Pod Autoscaler (optional)
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80