name: CI (tests)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Create venv & install deps
        run: |
          uv venv --python 3.12
          . .venv/bin/activate
          uv pip install -e .[dev]

      - name: Run tests (verbose)
        env:
          PYTEST_ADDOPTS: -vv -ra --maxfail=1 --durations=10 --color=yes --log-cli-level=INFO -o log_cli=true
        run: |
          . .venv/bin/activate
          uv run pytest
