name: Docker Publish (ECR)

on:
  push:
    branches: ["main"]      # produces :latest + :sha
    tags: ["v*.*.*"]        # produces :<semver> + :sha

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  ECR_REPO: ${{ vars.ECR_REPO || 'demo-app' }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # <-- ensure tags/history available

      - name: Debug ref
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "Event: ${{ github.event_name }}"

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: ecr-publish-${{ github.run_id }}

      - name: Ensure ECR image repo exists
        run: |
          aws ecr describe-repositories --repository-names "${ECR_REPO}" >/dev/null 2>&1 || \
            aws ecr create-repository --repository-name "${ECR_REPO}" >/dev/null

      - name: Login to Amazon ECR (Docker)
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_URI }}
          tags: |
            # Release tags:  v1.2.3 -> 1.2.3
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            # Main branch gets :latest
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # Always add a sha tag for traceability
            type=sha

      - name: Show computed tags
        run: |
          echo "TAGS:"
          echo "${{ steps.meta.outputs.tags }}" | tr ' ' '\n'

      - name: Build and push image to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
