name: Docker Publish (ECR)
on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  ECR_REPO: ${{ vars.ECR_REPO || 'demo-app' }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO }}
    steps:
      - uses: actions/checkout@v5
      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: ecr-publish-${{ github.run_id }}
      - name: Ensure ECR image repo exists
        run: |
          aws ecr describe-repositories --repository-names "${ECR_REPO}" >/dev/null 2>&1 || \
            aws ecr create-repository --repository-name "${ECR_REPO}" >/dev/null
      - name: Login to Amazon ECR (Docker)
        uses: aws-actions/amazon-ecr-login@v2
      - name: Generate Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_URI }}
          tags: |
            # For release tags: create semantic tags (1.2.3, etc.)
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            # For main branch: always push a "latest" tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # Always include a SHA fallback for traceability
            type=sha
      - name: Build and push image to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
