name: release-please

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GHA_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
